FROM python:3.11 as build-env
WORKDIR /app
COPY app/requirements.txt .
#USER nonroot
RUN pip install -r requirements.txt



# Distroless stage
FROM cgr.dev/chainguard/python:latest
#COPY --from=build-env /home/nonroot/.local/lib/python3.11/site-packages /home/nonroot/.local/lib/python3.11/site-packages
COPY --from=build-env /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY --from=build-env /usr/local/bin/flask /usr/local/bin/flask
#COPY app.py .
#CMD ["app.py"]


COPY app/app.py .
COPY app/templates templates/
COPY app/static static/
EXPOSE 5000
#ENTRYPOINT ["flask", "run", "--host=0.0.0.0"]
ENTRYPOINT ["python", "app.py"]
