apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: giropops-senhas
  name: giropops-senhas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: giropops-senhas
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: giropops-senhas
    spec:
      containers:
      - image: shrtkv/linuxtips-giropops-senhas:safe
        name: giropops-app
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          value: redis-service 
        resources:
          limits:
            cpu: "1"
            memory: "500Mi"
          requests:
            cpu: "500m"
            memory: "250Mi"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-service
  name: redis-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redis-service
    spec:
      containers:
      - image: cgr.dev/chainguard/redis:latest
        name: redis-service
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "1"
            memory: "500Mi"
          requests:
            cpu: "500m"
            memory: "250Mi"

