apiVersion: v1
kind: Service
metadata:
  name: giropops-senhas
spec:
  type: NodePort
  selector:
    app: giropops-senhas
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis-service
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: giropops-metrics
spec:
  # type: NodePort
  selector:
    app: giropops-senhas
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
      # nodePort: 30008
  type: ClusterIP
